[2025-07-11T15:36:24.307+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T15:36:24.325+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T15:36:24.326+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-11T15:36:24.357+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): loading_data> on 2025-07-10 00:00:00+00:00
[2025-07-11T15:36:24.369+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2025-07-11T15:36:24.386+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'flight_etl_dag', 'loading_data', 'scheduled__2025-07-10T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/flight_etl_dag.py', '--cfg-path', '/tmp/tmp7x5nd0o5']
[2025-07-11T15:36:24.389+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask loading_data
[2025-07-11T15:36:24.513+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [running]> on host c93b05155523
[2025-07-11T15:36:24.617+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flight_etl_dag' AIRFLOW_CTX_TASK_ID='loading_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-10T00:00:00+00:00'
[2025-07-11T15:36:24.668+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/load.py", line 13, in load_to_db
    create_tables(conn)
TypeError: create_tables() takes 0 positional arguments but 1 was given
[2025-07-11T15:36:24.685+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_etl_dag, task_id=loading_data, execution_date=20250710T000000, start_date=20250711T153624, end_date=20250711T153624
[2025-07-11T15:36:24.701+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task loading_data (create_tables() takes 0 positional arguments but 1 was given; 102)
[2025-07-11T15:36:24.714+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-11T15:36:24.735+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-11T16:00:59.313+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T16:00:59.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T16:00:59.327+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-11T16:00:59.345+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): loading_data> on 2025-07-10 00:00:00+00:00
[2025-07-11T16:00:59.351+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2025-07-11T16:00:59.356+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'flight_etl_dag', 'loading_data', 'scheduled__2025-07-10T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/flight_etl_dag.py', '--cfg-path', '/tmp/tmpw6at1bh2']
[2025-07-11T16:00:59.358+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask loading_data
[2025-07-11T16:00:59.436+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_etl_dag.loading_data scheduled__2025-07-10T00:00:00+00:00 [running]> on host faee04e61171
[2025-07-11T16:00:59.514+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flight_etl_dag' AIRFLOW_CTX_TASK_ID='loading_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-10T00:00:00+00:00'
[2025-07-11T16:00:59.527+0000] {logging_mixin.py:188} INFO - Data to load:
[2025-07-11T16:00:59.528+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/load.py", line 14, in load_to_db
    print(df.head())
UnboundLocalError: local variable 'df' referenced before assignment
[2025-07-11T16:00:59.541+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_etl_dag, task_id=loading_data, execution_date=20250710T000000, start_date=20250711T160059, end_date=20250711T160059
[2025-07-11T16:00:59.555+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task loading_data (local variable 'df' referenced before assignment; 92)
[2025-07-11T16:00:59.570+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-11T16:00:59.586+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
